"""change_faq_embedding_to_vector_type

Revision ID: 699f48bb78e6
Revises: 
Create Date: 2025-05-15 11:33:23.099619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector # Import Vector


# revision identifiers, used by Alembic.
revision: str = '699f48bb78e6'
down_revision: Union[str, None] = '0001_initial' # Assuming '0001_initial' is the previous migration. User should verify this.
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faqs', sa.Column('embedding', Vector(1536), nullable=True))
    # If the old column was also named 'embedding' and was JSON, 
    # and you want to remove it first (if it wasn't automatically handled by a type change):
    # op.drop_column('faqs', 'embedding_old_json_name') # Or whatever the old column was if different
    # Or, if altering the existing column (syntax might vary based on DB and if data exists):
    # op.alter_column('faqs', 'embedding',
    #               existing_type=sa.JSON(),
    #               type_=Vector(1536),
    #               nullable=True,
    #               postgresql_using='embedding::text::vector') # Example conversion, might not work for JSON to Vector
    # For simplicity and given it was nullable, we are adding a new column or assuming autogenerate would handle simple type change.
    # If it was a JSON column named 'embedding', it might have been dropped by autogen if it detected a type change, 
    # or this add_column might fail if it still exists. 
    # A safer approach if the column 'embedding' of type JSON exists is to drop it first.
    # op.drop_column('faqs', 'embedding') # Uncomment if 'embedding' JSON column still exists
    # op.add_column('faqs', sa.Column('embedding', Vector(1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faqs', 'embedding')
    # If you had an old JSON column, you might want to recreate it here:
    # op.add_column('faqs', sa.Column('embedding', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

