"""change_faq_embedding_to_vector_type

Revision ID: 699f48bb78e6
Revises: manual_faq_creation
Create Date: 2025-05-15 11:33:23.099619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector # Import Vector


# revision identifiers, used by Alembic.
revision: str = '699f48bb78e6'
down_revision: Union[str, None] = 'manual_faq_creation' # CORRECTED: Points to the migration that creates faqs table
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema to change embedding column type."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faqs',
                    'embedding',
                    existing_type=sa.LargeBinary(),
                    type_=Vector(1536),
                    nullable=True,
                    # If direct type alteration is not supported or data transformation is needed:
                    # postgresql_using='embedding::text::vector' # This is an example and might not be correct for LargeBinary to Vector
                    # For pgvector, often a direct type alter works if the extension is enabled.
                   )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema to revert embedding column type."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faqs',
                    'embedding',
                    existing_type=Vector(1536),
                    type_=sa.LargeBinary(),
                    nullable=True
                   )
    # ### end Alembic commands ###

