# api/schemas/rag.py
from pydantic import BaseModel, Field

class RAGQueryRequest(BaseModel):
    tenant_id: str = Field(..., description="The ID of the tenant for whom the query is made.")
    query: str = Field(..., description="The user's query to the RAG system.")

class RAGResponse(BaseModel):
    answer: str = Field(..., description="The answer generated by the RAG system.")
    tenant_id: str = Field(..., description="The ID of the tenant for whom the query was made.")
    query: str = Field(..., description="The original user query.")
    # Potentially add retrieved_context or source_faqs_ids for debugging/transparency
  
